sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: ${DB_PWD}
  alioss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    access-key-id: ${ALI_OSS_KEY_ID}
    access-key-secret: ${ALI_OSS_KEY_SECRET}
    bucket-name: takeaway-project-klr
  redis:
    host: localhost
    port: 6379
    auth:
    database: 10